sudo: required

cache:
  directories:
  - "$HOME/.ivy2"
  - "$HOME/.sbt"

services:
  - docker

language: scala

scala:
  - 2.11.7

jdk:
  - oraclejdk8

before_script:
  - openssl aes-256-cbc -K $encrypted_6a59c36769db_key -iv $encrypted_6a59c36769db_iv -in .travis.cert.tar.enc -out .travis.cert.tar -d
  - tar xf .travis.cert.tar
  - docker login -u=travis -p="$DOCKER_PASSWORD" https://strawpay-dockerv2-local.jfrog.io

script:
  - sbt ++$TRAVIS_SCALA_VERSION -J-XX:ReservedCodeCacheSize=256M test docker:publish versionFile
#  - curl -f -X POST -H "Content-Type:application/json" --cacert strawpayca.crt --cert travis.pem -d @target/version.json "https://rocannon.strawpay.com/internal/rocannon.yaml?buildNumber=$TRAVIS_BUILD_NUMBER%28$TRAVIS_COMMIT%29"
  
after_script:
  - rm -f $HOME/.docker/config.json
  - rm -f travis.pem strawpayca.crt .travis.cert.tar
  - find $HOME/.sbt -name "*.lock" -exec rm {} \;
  - find $HOME/.ivy2 -name "ivydata-*.properties" -exec rm {} \;
  
env:
  global:
      - secure: "pFS7+MjvrD89Xweh68tLgI29rXMKdNJJg/2iPoptHSqvB6i+sKFRSrmiQd+GGzXZz5NLNN9wc04pan6ScMI+JuOg/QNoH0IOxXOqEaNZYETkDmUwrTnx48Vc9DKpSNEeEeIGhdHaw4KndOyypLPbsnegyjsnnl6SqjUIkW1nu5UUKPl49gRCcb4cl+Uzxv2sv14CjDmrLfSIV8lIXDUWgIqZtZ5QWujgutZJTaiqF5se4tFD9sCOP+il9RElykNHiRLvqBEVEBqBCfMU2wfFVIRn+iROJCliwQIj0if4COoUr4jJ2J6zViiWrCN3SrqkWgNLXl5biEic/2XNjs9c0/dB4ElgG85U+7wbq7IJJWSVruPZdUxPiK/a20/hMqcywa627VcDEsThCO9jQUmimUReDgbmpb243zwHbSAX6mRbzDXgNrK/bxz+CcLZQ0YetaDP8M0jKOz6cQkNm5cFaG/2p9HAJfp4whvqhrb1fUOW3xJM1SHokqKCkFklo8y07nd7p0KOzVR9m6NLezmOMc7vpLvQoyzRxP9rTEGukxe3w9MbmF8FMvr5OSBpZdjE7iErA5ADT5AGxIOCSQsqGs818vd9TsZm9mYBGYUSZOqD3jcOQ3vi3UAQUdM+E0WMugyv69DfY9+81IMFKwwHLplGWoDT1uj/FG490fRWaeo="


notifications:
  slack:
    secure: "gw3GIDgJxrzt0Zd/+1fA6PfU8ZKzCU5CTne5w3g61dyFFzW8lR8BQEJJyy+nYlgKYpqn99+RYrw1TuPoMayZzePIy1qDPewTBDiZxe8k3yreSnOAvzzr7pl1h8sV6hJhlp/VXxrpZBDPJjnQnUJM9q1ddNANDKLlujYFY08xeXChM1/8Rwu6J16fM7Y81TFufTDLhuOpIFj8TDWPVgfJ1Gkn4yfy95Mh+xa5m7gX+uK2DthEqvgCCjHmrQPmv1rJeAWbzvEv+Uv38uosHBc3rNL3Dg3BUz0JSTdpr1//g5p6kn4yyJM6eTDP7/NH75+bxbwHBCSfsedJ0Sx+xSy1ZJP30rRTykodaE17G3ekiOFYz7zsvYA9IJAz/daTOEywYHPnaKaq0SxJsSUSCb5m/4S6snsHYF/YcNASd+MfE7q8TINVSu6NPtO2BFgVmx1j2pYxWFj6YXGq9nA5S8zH0rmdniSQP9CIVBCLXFm7P60O/lTw8xgehMaaswsnP7S7aWX64ORKQTby6SEIWB2Kx6PlYqoQYYjpfeKlOFWywXY3VCQq/DxF4kDaq6uU8tF6lEIdF/ol28vDDyNnue4m37/PX/5X/T1EJnzCtV1tRPGR3CQrxYgW9xaPkGc89c9GRhhZMnoHLKlUE40QSEywL5KinhPsGrKSHL0b9ZsM2uY="
